---
url: "http://localhost:8080"
database:
  host: "pgdb"
  dbname: "nflix"
  user: "postgres"
  password: "qaninja"
api:
  movies: "http://localhost:3002"
users:
  cat_manager:
    email: "tony@stark.com"
    pass: "pwd123"