---
url: "http://localhost"
database:
  host: "104.237.137.68"
  dbname: "nflix"
  user: "postgres"
  password: "qaninja"
api:
  movies: "http://localhost:3002"
users:
  cat_manager:
      email: "tony@stark.com"
      pass: "pwd123"
  admin:
      email: "admin@nflix.com"
      pass: "admin123"